-- 기존 테이블 삭제
DROP TABLE TBL_MEMBER;
DROP TABLE TBL_PT_AMOUNT;
DROP TABLE TBL_TRAINER_INFO;
DROP TABLE TBL_MEMBER_MODIFIED_HISTORY;

-- 기존 시퀀스 삭제
DROP SEQUENCE SEQ_MEMBER_NO;

-- 기존 트리거 삭제
DROP TRIGGER MEMBER_HISTORY_TRIGGER;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO;

-- 테이블 생성
-- MEMBER 테이블 생성
CREATE TABLE TBL_MEMBER(
  MEMBER_NO NUMBER PRIMARY KEY,
  EMAIL VARCHAR2(50) UNIQUE NOT NULL,
  MEMBER_PWD VARCHAR2(255) NOT NULL,
  MEMBER_NAME VARCHAR2(20) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFIED_DATE DATE,
  BLACK_STATUS VARCHAR(2) DEFAULT 'N' CHECK(BLACK_STATUS IN ('Y', 'N')),
  MEMBER_ROLE VARCHAR2(15) DEFAULT 'MEMBER' CHECK(MEMBER_ROLE IN ('MEMBER', 'TRAINER', 'ADMIN')),
  MEMBER_STATUS VARCHAR2(2) DEFAULT 'Y' CHECK(MEMBER_STATUS IN ('Y', 'N'))
);

-- 관리자 계정 추가
		INSERT
		  INTO TBL_MEMBER A
		(
		  A.MEMBER_NO
		, A.EMAIL
		, A.MEMBER_PWD
		, A.MEMBER_NAME
		, A.PHONE
        , A.MEMBER_ROLE
		)
		VALUES
		(
		  SEQ_MEMBER_NO.NEXTVAL
		, 'hellopt@gmail.com'
		, '$2a$10$7NqnZ0pUQh2RDLDkcEmubOSWB2DSewpDNs7q7xwxgZHHvMgZGJ.rW'
		, '관리자'
		, '01012345678'
        , 'ADMIN'
		);
commit;

-- (PT)회차권잔여수량 테이블 생성
CREATE TABLE TBL_PT_AMOUNT(
  MEMBER_NO NUMBER PRIMARY KEY REFERENCES TBL_MEMBER(MEMBER_NO),
  PT_AMOUNT NUMBER DEFAULT 0
);

-- 트레이너추가정보 테이블 생성
CREATE TABLE TBL_TRAINER_INFO(
  MEMBER_NO NUMBER PRIMARY KEY REFERENCES TBL_MEMBER(MEMBER_NO),
  ACCOUNT_NUMBER VARCHAR2(50),
  BANK_NAME VARCHAR2(30),
  ACCOUNT_HOLDER VARCHAR2(40),
  APPROVAL_STATUS VARCHAR2(2),
  AVERAGE_SCORE NUMBER
);

-- 회원정보수정이력 테이블 생성
CREATE TABLE TBL_MEMBER_MODIFIED_HISTORY(
  MEMBER_NO NUMBER REFERENCES TBL_MEMBER(MEMBER_NO),
  MEMBER_PWD VARCHAR2(255) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  MEMBER_STATUS VARCHAR2(2) NOT NULL,
  BLACK_STATUS VARCHAR2(2) NOT NULL,
  MODIFIED_DATE DATE
);
-- 회원정보수정 히스토리를 위한 트리거 생성
CREATE OR REPLACE TRIGGER MEMBER_HISTORY_TRIGGER
  AFTER UPDATE
  ON TBL_MEMBER
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
  BEGIN
    IF UPDATING
      THEN
        INSERT
          INTO TBL_MEMBER_MODIFIED_HISTORY
        (
          MEMBER_NO
        , MEMBER_PWD
        , PHONE
        , MEMBER_STATUS
        , BLACK_STATUS
        , MODIFIED_DATE
        )
        VALUES
        (
          NVL(:NEW.MEMBER_NO,:OLD.MEMBER_NO)
        , NVL(:NEW.MEMBER_PWD,:OLD.MEMBER_PWD)
        , NVL(:NEW.PHONE,:OLD.PHONE)
        , NVL(:NEW.MEMBER_STATUS,:OLD.MEMBER_STATUS)
        , NVL(:NEW.BLACK_STATUS,:OLD.BLACK_STATUS)
        , NVL(:NEW.MODIFIED_DATE,:OLD.MODIFIED_DATE)
        );
    END IF;
END;
/

-- 공지사항 테이블 생성

-- 카테고리 테이블 생성

-- 카테고리 테이블에 카테고리 추가

-- 게시판 테이블 생성

-- 첨부파일 테이블 생성